import React from "react";
import '../Components/Styles/About.css'

const Aboutus =() =>{return(<div className="container">



    <h3 className="navy fw-bold f3">Who we are:</h3>
    <p className="f4 fw5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices in iaculis nunc sed augue lacus. Ut aliquam purus sit amet luctus venenatis lectus. Natoque penatibus et magnis dis parturient montes. Feugiat scelerisque varius morbi enim nunc faucibus. Arcu bibendum at varius vel pharetra vel turpis. Ac turpis egestas sed tempus urna et pharetra pharetra. Commodo nulla facilisi nullam vehicula ipsum a arcu. Cras sed felis eget velit aliquet sagittis. Feugiat in ante metus dictum at tempor commodo ullamcorper. Pharetra pharetra massa massa ultricies. Id porta nibh venenatis cras sed felis eget. Quis varius quam quisque id diam vel quam elementum pulvinar. Diam in arcu cursus euismod.

Nunc faucibus a pellentesque sit amet porttitor. Fames ac turpis egestas maecenas pharetra convallis. Rhoncus mattis rhoncus urna neque viverra. Lacus sed viverra tellus in. Iaculis urna id volutpat lacus laoreet non curabitur. Commodo odio aenean sed adipiscing diam donec adipiscing. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Vestibulum lorem sed risus ultricies. Commodo elit at imperdiet dui accumsan sit amet. Mauris ultrices eros in cursus turpis massa tincidunt. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque.

Nunc mattis enim ut tellus elementum sagittis vitae et. Viverra accumsan in nisl nisi. Odio morbi quis commodo odio. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Nec tincidunt praesent semper feugiat nibh. Dignissim convallis aenean et tortor at risus. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Mi sit amet mauris commodo quis. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Enim nulla aliquet porttitor lacus luctus. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Felis eget velit aliquet sagittis id. Mi tempus imperdiet nulla malesuada pellentesque elit. Et tortor at risus viverra adipiscing at in. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Laoreet suspendisse interdum consectetur libero id faucibus. Pellentesque nec nam aliquam sem et tortor. Integer malesuada nunc vel risus commodo.

Sagittis orci a scelerisque purus semper eget duis at. Sem nulla pharetra diam sit amet nisl suscipit. Nec nam aliquam sem et. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Amet mauris commodo quis imperdiet massa tincidunt nunc. Euismod elementum nisi quis eleifend. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Gravida quis blandit turpis cursus in hac habitasse. Adipiscing elit ut aliquam purus sit amet luctus. Convallis convallis tellus id interdum velit laoreet id donec. At auctor urna nunc id cursus metus aliquam eleifend. Risus quis varius quam quisque id diam vel quam elementum. Mauris augue neque gravida in fermentum et sollicitudin ac. Odio facilisis mauris sit amet massa. A pellentesque sit amet porttitor eget dolor morbi non. Mauris in aliquam sem fringilla. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.

Dictum at tempor commodo ullamcorper a. Pharetra et ultrices neque ornare aenean euismod elementum. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Risus at ultrices mi tempus imperdiet nulla malesuada. Vitae justo eget magna fermentum iaculis eu non diam. Duis convallis convallis tellus id interdum velit laoreet id donec. Odio euismod lacinia at quis risus sed vulputate. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Integer enim neque volutpat ac tincidunt vitae. Elementum nibh tellus molestie nunc non. Libero volutpat sed cras ornare arcu. Quisque sagittis purus sit amet volutpat. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Pellentesque nec nam aliquam sem et tortor. A condimentum vitae sapien pellentesque habitant morbi tristique senectus.</p>

<h3 className="navy fw-bold f3">Our Mission:</h3>

<p className="f4 fw5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices in iaculis nunc sed augue lacus. Ut aliquam purus sit amet luctus venenatis lectus. Natoque penatibus et magnis dis parturient montes. Feugiat scelerisque varius morbi enim nunc faucibus. Arcu bibendum at varius vel pharetra vel turpis. Ac turpis egestas sed tempus urna et pharetra pharetra. Commodo nulla facilisi nullam vehicula ipsum a arcu. Cras sed felis eget velit aliquet sagittis. Feugiat in ante metus dictum at tempor commodo ullamcorper. Pharetra pharetra massa massa ultricies. Id porta nibh venenatis cras sed felis eget. Quis varius quam quisque id diam vel quam elementum pulvinar. Diam in arcu cursus euismod.

Nunc faucibus a pellentesque sit amet porttitor. Fames ac turpis egestas maecenas pharetra convallis. Rhoncus mattis rhoncus urna neque viverra. Lacus sed viverra tellus in. Iaculis urna id volutpat lacus laoreet non curabitur. Commodo odio aenean sed adipiscing diam donec adipiscing. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Vestibulum lorem sed risus ultricies. Commodo elit at imperdiet dui accumsan sit amet. Mauris ultrices eros in cursus turpis massa tincidunt. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque.

Nunc mattis enim ut tellus elementum sagittis vitae et. Viverra accumsan in nisl nisi. Odio morbi quis commodo odio. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Nec tincidunt praesent semper feugiat nibh. Dignissim convallis aenean et tortor at risus. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Mi sit amet mauris commodo quis. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Enim nulla aliquet porttitor lacus luctus. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Felis eget velit aliquet sagittis id. Mi tempus imperdiet nulla malesuada pellentesque elit. Et tortor at risus viverra adipiscing at in. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Laoreet suspendisse interdum consectetur libero id faucibus. Pellentesque nec nam aliquam sem et tortor. Integer malesuada nunc vel risus commodo.

Sagittis orci a scelerisque purus semper eget duis at. Sem nulla pharetra diam sit amet nisl suscipit. Nec nam aliquam sem et. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Amet mauris commodo quis imperdiet massa tincidunt nunc. Euismod elementum nisi quis eleifend. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Gravida quis blandit turpis cursus in hac habitasse. Adipiscing elit ut aliquam purus sit amet luctus. Convallis convallis tellus id interdum velit laoreet id donec. At auctor urna nunc id cursus metus aliquam eleifend. Risus quis varius quam quisque id diam vel quam elementum. Mauris augue neque gravida in fermentum et sollicitudin ac. Odio facilisis mauris sit amet massa. A pellentesque sit amet porttitor eget dolor morbi non. Mauris in aliquam sem fringilla. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.

Dictum at tempor commodo ullamcorper a. Pharetra et ultrices neque ornare aenean euismod elementum. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Risus at ultrices mi tempus imperdiet nulla malesuada. Vitae justo eget magna fermentum iaculis eu non diam. Duis convallis convallis tellus id interdum velit laoreet id donec. Odio euismod lacinia at quis risus sed vulputate. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Integer enim neque volutpat ac tincidunt vitae. Elementum nibh tellus molestie nunc non. Libero volutpat sed cras ornare arcu. Quisque sagittis purus sit amet volutpat. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Pellentesque nec nam aliquam sem et tortor. A condimentum vitae sapien pellentesque habitant morbi tristique senectus.</p>



<h3 className="navy fw-bold f3">Why train with us?</h3>

<p className="f4 fw5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. A iaculis at erat pellentesque. Ante metus dictum at tempor commodo ullamcorper a lacus vestibulum. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. At elementum eu facilisis sed odio. Elit sed vulputate mi sit amet mauris commodo quis imperdiet. Sit amet tellus cras adipiscing enim eu turpis egestas. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Etiam non quam lacus suspendisse faucibus interdum. Urna molestie at elementum eu facilisis. Erat velit scelerisque in dictum non consectetur. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Sagittis orci a scelerisque purus semper eget duis at. Id consectetur purus ut faucibus pulvinar elementum. Diam in arcu cursus euismod quis viverra. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Lacus vestibulum sed arcu non odio euismod. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Neque convallis a cras semper auctor neque vitae tempus quam.

Gravida in fermentum et sollicitudin ac. Cras adipiscing enim eu turpis egestas pretium aenean. Lacus sed turpis tincidunt id aliquet risus feugiat. Ut porttitor leo a diam sollicitudin tempor id eu. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Diam quis enim lobortis scelerisque fermentum dui faucibus. Aliquet porttitor lacus luctus accumsan tortor posuere ac. A condimentum vitae sapien pellentesque. Lectus urna duis convallis convallis tellus id interdum. Nibh sit amet commodo nulla facilisi nullam. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Vulputate mi sit amet mauris commodo quis imperdiet massa. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Neque ornare aenean euismod elementum nisi. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Sapien pellentesque habitant morbi tristique senectus et netus et. Ultrices in iaculis nunc sed augue lacus viverra.

Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Orci eu lobortis elementum nibh tellus molestie. Odio euismod lacinia at quis risus sed vulputate odio. Etiam erat velit scelerisque in dictum. Ultrices sagittis orci a scelerisque purus semper eget. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Nullam eget felis eget nunc lobortis mattis aliquam. Donec ultrices tincidunt arcu non sodales. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Velit sed ullamcorper morbi tincidunt. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Potenti nullam ac tortor vitae purus. At ultrices mi tempus imperdiet. Ut pharetra sit amet aliquam id diam. Augue eget arcu dictum varius duis. A iaculis at erat pellentesque. Integer vitae justo eget magna. Arcu dui vivamus arcu felis bibendum ut tristique et.

Sit amet venenatis urna cursus. Ipsum suspendisse ultrices gravida dictum fusce ut. Ligula ullamcorper malesuada proin libero. Ridiculus mus mauris vitae ultricies. Massa tincidunt dui ut ornare lectus sit amet. Morbi non arcu risus quis varius. Dolor purus non enim praesent elementum facilisis leo. Donec et odio pellentesque diam. Vel pretium lectus quam id leo in vitae turpis massa. Lectus mauris ultrices eros in cursus turpis massa.

Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Sed vulputate odio ut enim blandit. Curabitur vitae nunc sed velit dignissim sodales ut eu. Tortor at risus viverra adipiscing at in. Imperdiet sed euismod nisi porta lorem mollis aliquam. Sodales ut eu sem integer vitae justo. Eleifend donec pretium vulputate sapien nec sagittis. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Id neque aliquam vestibulum morbi blandit cursus risus at. In massa tempor nec feugiat nisl pretium. Quam viverra orci sagittis eu volutpat. Dictum at tempor commodo ullamcorper a lacus. Libero enim sed faucibus turpis in eu mi. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius.</p>

<h3 className="navy fw-bold f3">Our policy and training enviroment:</h3>
<p className="f4 fw5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices in iaculis nunc sed augue lacus. Ut aliquam purus sit amet luctus venenatis lectus. Natoque penatibus et magnis dis parturient montes. Feugiat scelerisque varius morbi enim nunc faucibus. Arcu bibendum at varius vel pharetra vel turpis. Ac turpis egestas sed tempus urna et pharetra pharetra. Commodo nulla facilisi nullam vehicula ipsum a arcu. Cras sed felis eget velit aliquet sagittis. Feugiat in ante metus dictum at tempor commodo ullamcorper. Pharetra pharetra massa massa ultricies. Id porta nibh venenatis cras sed felis eget. Quis varius quam quisque id diam vel quam elementum pulvinar. Diam in arcu cursus euismod.

Nunc faucibus a pellentesque sit amet porttitor. Fames ac turpis egestas maecenas pharetra convallis. Rhoncus mattis rhoncus urna neque viverra. Lacus sed viverra tellus in. Iaculis urna id volutpat lacus laoreet non curabitur. Commodo odio aenean sed adipiscing diam donec adipiscing. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Vestibulum lorem sed risus ultricies. Commodo elit at imperdiet dui accumsan sit amet. Mauris ultrices eros in cursus turpis massa tincidunt. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque.

Nunc mattis enim ut tellus elementum sagittis vitae et. Viverra accumsan in nisl nisi. Odio morbi quis commodo odio. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Nec tincidunt praesent semper feugiat nibh. Dignissim convallis aenean et tortor at risus. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Mi sit amet mauris commodo quis. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Enim nulla aliquet porttitor lacus luctus. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Felis eget velit aliquet sagittis id. Mi tempus imperdiet nulla malesuada pellentesque elit. Et tortor at risus viverra adipiscing at in. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Laoreet suspendisse interdum consectetur libero id faucibus. Pellentesque nec nam aliquam sem et tortor. Integer malesuada nunc vel risus commodo.

Sagittis orci a scelerisque purus semper eget duis at. Sem nulla pharetra diam sit amet nisl suscipit. Nec nam aliquam sem et. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Amet mauris commodo quis imperdiet massa tincidunt nunc. Euismod elementum nisi quis eleifend. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Gravida quis blandit turpis cursus in hac habitasse. Adipiscing elit ut aliquam purus sit amet luctus. Convallis convallis tellus id interdum velit laoreet id donec. At auctor urna nunc id cursus metus aliquam eleifend. Risus quis varius quam quisque id diam vel quam elementum. Mauris augue neque gravida in fermentum et sollicitudin ac. Odio facilisis mauris sit amet massa. A pellentesque sit amet porttitor eget dolor morbi non. Mauris in aliquam sem fringilla. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.

Dictum at tempor commodo ullamcorper a. Pharetra et ultrices neque ornare aenean euismod elementum. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Risus at ultrices mi tempus imperdiet nulla malesuada. Vitae justo eget magna fermentum iaculis eu non diam. Duis convallis convallis tellus id interdum velit laoreet id donec. Odio euismod lacinia at quis risus sed vulputate. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Integer enim neque volutpat ac tincidunt vitae. Elementum nibh tellus molestie nunc non. Libero volutpat sed cras ornare arcu. Quisque sagittis purus sit amet volutpat. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. Pellentesque nec nam aliquam sem et tortor. A condimentum vitae sapien pellentesque habitant morbi tristique senectus.</p>
    
</div>)}

export default Aboutus;